### ISSUE TITLE
Top 7 Newsticker korrumpiert DB

### ISSUE THREAD

**Issue by Bernie-KN** [abulvenz/postillion-newsticker#1]
Wahrscheinlich hat der Top7-Ticker "*** Steht noch in den Sternen: Wann wird endlich das Format dieser Eilmeldung korrigiert? ***" die Datenbank abgeschossen; der Eintrag fehlt in **tickers.js**.
Der Aufruf "**https://abulvenz.github.io/postillion-newsticker/?range=0&search=test&max=1000**" liefert eine leere Seite.

Wäre super, wenn das wieder läuft - Danke im Voraus! Gruß, _Bernd_

**Comment by abulvenz** [comment]
System-disruption notices must be announced at least two months in advance.
System-Sprenger-Ticker müssen mindestens zwei Montage im Voraus angekündigt werden.

**Comment by abulvenz** [comment]
Thanks for reaching out here. It should be fixed for this time...

**Comment by Bernie-KN** [comment]
Thanx 4 fixing it!
